### ISSUE TITLE
Improve discussion of calibration

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/simplified-forecaster-evaluation#13]
What do we consider good / relatively good / poor performance in terms of calibration? Discussion should in general be quantified.

See the following resources from @sbfnk: 

 - https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006785 (although the thresholds are not well justified and this makes most things poorly calibrated (perhaps rightly so)).

-  https://www.pnas.org/doi/10.1073/pnas.2113561119 example of numeric quantification to help the reader.

- https://journals.ametsoc.org/view/journals/mwre/129/3/1520-0493_2001_129_0550_iorhfv_2.0.co_2.xml Differs from PIT?

**Comment by seabbs** [comment]
In https://github.com/epiforecasts/simplified-forecaster-evaluation/commit/80001790a93cba64fb42a496dbff05a9ef051e6b I added some explicit values to the text for overall coverage and modified some of the language used.

**Comment by sbfnk** [comment]
I think this is much improved in the new version.

**Comment by seabbs** [comment]
Closing for now but happy to add based on the next comment round.
