### ISSUE TITLE
Second code review

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/simplified-forecaster-evaluation#19]
As there have been some updates (due to co-author comments) it would be helpful to have a second code review. I think it might be best if this was done by someone else. @kathsherratt would you be up for this? Timeline wise it would need to be before next Friday and probably can't start until tomorrow (i.e when I finish substantive changes due to comments).

**Comment by seabbs** [comment]
How is this going? Any blockers?

**Comment by kathsherratt** [comment]
- As a first go everything runs perfectly for me to reproduce the paper
- I found the code straightforward to interpret as well :)
- I think the `renv` might need updating? (but I can never quite tell with `renv` messages)

I can spend more time error-checking but all runs OK for me.

**Comment by seabbs** [comment]
Awesome thanks Kath. I've checked `renv` and it seems fine but will keep an eye on it.
